# -*- coding: utf-8 -*-
"""ATM-withdrawal-system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xuziazyauQCKTR_JbJ0ltcBLqNqpbXRd
"""

def withdraw(balance, amount):

 if amount <= 0:
        print("Amount must be greater than 0")
 elif amount > balance:
        print("Insufficient Balance")
 else:
        balance = balance - amount
        print("Withdrawal successful")
        print("Remaining Balance:", balance)

        if balance < 500:
            print("Warning: Low Balance")



balance = int(input("enter your balance: "))
amount = int(input("enter your withdrawal: "))

withdraw(balance, amount)