# -*- coding: utf-8 -*-
"""car-rental-system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PBTAgOoV1jvy4-nNmAG0ELUZPlqfICZn
"""

def calculate_rental(car_type, days, driver=False):

    # Car rates
    if car_type == "economy":
        rate = 3000

    elif car_type == "sedan":
        rate = 5000

    elif car_type == "suv":
        rate = 8000

    else:
        print("Invalid car type")
        return

    # Car cost
    car_cost = rate * days

    # Driver cost
    if driver == True:
        driver_cost = 2000 * days
    else:
        driver_cost = 0

    # Subtotal
    subtotal = car_cost + driver_cost

    # Discount
    if days >= 7:
        discount = subtotal * 0.15

    elif days >= 3:
        discount = subtotal * 0.10

    else:
        discount = 0

    # Final bill
    final_bill = subtotal - discount

    # Display
    print("Car Cost:", car_cost)
    print("Driver Cost:", driver_cost)
    print("Discount:", discount)
    print("Final Bill:", final_bill)


# Taking input from user
car_type = input("Enter car type (economy/sedan/suv): ").lower()
days = int(input("Enter number of days: "))

driver_input = input("Driver required? (yes/no): ").lower()

if driver_input == "yes":
    driver = True
else:
    driver = False

calculate_rental(car_type, days, driver)