# -*- coding: utf-8 -*-
"""Credit-Card-Transaction-Validator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lzM-McsUIqgzTI0h-u0W7ryw6G6lKuGQ
"""

def validate_transaction(balance, amount, daily_limit, used_today):

    if amount <= 0:
        print("Transaction Rejected")
        print("Reason: Transaction amount must be greater than 0")

    elif amount > balance:
        print("Transaction Rejected")
        print("Reason: Insufficient balance")

    elif balance - amount < 1000:
        print("Transaction Rejected")
        print("Reason: Minimum remaining balance should be Rs. 1,000")

    elif used_today + amount > daily_limit:
        print("Transaction Rejected")
        print("Reason: Daily transaction limit exceeded")

    else:
        remaining_balance = balance - amount
        remaining_daily_limit = daily_limit - (used_today + amount)

        print("Transaction Approved")
        print("Remaining Balance:", remaining_balance)
        print("Remaining Daily Limit:", remaining_daily_limit)


validate_transaction(50000, 10000, 20000, 5000)