# -*- coding: utf-8 -*-
"""Student-grade-calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rvwZ2drkk0QOUPsUxZLbGZ_sTbLt9U1N
"""

def calculate_result(Name, English, Math, Computer):
  Total = English + Math + Computer
  percentage = (Total / 300) * 100

  if percentage >= 90:
    Grade = "A+"
  elif percentage >= 80:
    Grade = "A"
  elif percentage >= 70:
    Grade = "B"
  elif percentage >= 60:
    Grade = "C"
  elif percentage >= 50:
    Grade = "D"

  else:
    Grade = "F"




  print("Student_Name:", Name)
  print("Total:", Total)
  print("percentage:", percentage)
  print("Grade:", Grade)


Name = input("Enter Your Name ?")
English = int(input("Enter Your English Marks :"))
Math = int(input("Enter Your Math Marks :"))
Computer = int(input("Enter Your Computer Marks :"))


calculate_result(Name, English, Math, Computer)